### ISSUE TITLE
Weird Shadows

### ISSUE THREAD

**Issue by Irevol** [ClassicAdam/mt_block_and_asset_pack#1]
![screenshot_20240707_092112](https://github.com/ClassicAdam/mt_block_and_asset_pack/assets/141366212/04fdf186-e8db-4410-b04e-fa2d2a4799a5)
When multiple nodes from the mod are placed together, stuff like this happens. 
I see you've set `sunlight_propagates = true`, but you also need to set `paramtype = 'light'`

**Comment by ClassicAdam** [comment]
Thank you for the feedback!  I'll try to get a fix out in my next release.
